### ISSUE TITLE
Adaptation for VisiumHD?

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [JinmiaoChenLab/DeepST#30]
Hey, with the latest release of VisiumHD, the files have become huge (barcodes going from 5-10k to over 500k in the 8 micron bins). I noticed that the GrapST package isn't very optimized in the sense that there's a lot of "copies" being made from original files which end up blowing up memory consumption (over 100 GB for a file with 400k barcodes). I was wondering if there's a goal to optimize the code to be better at managing memory with VisiumHD data?

**Comment by longyahui** [comment]
Hi,

    Thank you for the great suggestion.

    Next, we would consider optimizing the memory issue. 

    Best regards,
    Yahui
