### ISSUE TITLE
Error while importing GraphST, No module named 'ot'

### ISSUE THREAD

**Issue by niklasbinder** [JinmiaoChenLab/DeepST#40]
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 from GraphST import GraphST

File ~/.local/lib/python3.8/site-packages/GraphST-1.1.1-py3.8.egg/GraphST/__init__.py:11
      8 __author__ = "Yahui Long"
      9 __email__ = "long_yahui@immunol.a-star.edu.sg"
---> 11 from .utils import clustering, project_cell_to_spot
     12 from .preprocess import preprocess_adj, preprocess, construct_interaction, add_contrastive_label, get_feature, permutation, fix_seed

File ~/.local/lib/python3.8/site-packages/GraphST-1.1.1-py3.8.egg/GraphST/utils.py:5
      3 from sklearn import metrics
      4 import scanpy as sc
----> 5 import ot
      6 from sklearn.decomposition import PCA
      9 def mclust_R(adata, num_cluster, modelNames='EEE', used_obsm='emb_pca', random_seed=2020):

ModuleNotFoundError: No module named 'ot'

**Comment by huixiaaaa** [comment]
You can try to run the following command to install the POT library: pip install POT

**Comment by niklasbinder** [comment]
it now works, thank you.
