### ISSUE TITLE
Cannot find file scalefactors_json.json when running tutorial 1.

### ISSUE THREAD

**Issue by JINJINT** [JinmiaoChenLab/DeepST#5]
Hi,

I was trying to reproduce tutorial 1 but it gives me the following error:

Could not find '151673/spatial/scalefactors_json.json'

Seems like scanpy updates its read_visium function and now the scalefactor is required? If so, where can I find/how can I get such a file?

Thank you very much! And also I really appreciate your impressive work and well-documented code.

Best,
Jinjin

**Comment by longyahui** [comment]
Hi Jinjin,

    Thank you for your attention.

    Please kindly find 'scalefactors_json.json' files for each sample of DLPFC by the link https://drive.google.com/drive/folders/19wBdOXFxBEmUV5Eb2UTCHSI7BDi-lNoV

    I hope it would be helpful for you. Thank you again.

    Best regards,
    Yahui
